task default: [ "manifests.nt", "earl.jsonld", "earl.ttl", "index.html" ]

desc "Create concatenated test manifests"
file "manifests.nt" => File.expand_path("../../tests/manifest.ttl", __FILE__) do
  require 'rdf'
  require 'json/ld'
  require 'rdf/ntriples'
  require 'rdf/turtle'
  graph = RDF::Graph.load(
    File.expand_path("../../tests/manifest.ttl", __FILE__),
    base_uri: "https://w3c.github.io/rdf-canon/tests/",
    unique_bnodes: true)
  puts "write"
  RDF::NTriples::Writer.open("manifests.nt", unique_bnodes: true, validate: false) {|w| w << graph}
end

desc "Build JSON-LD"
file "earl.jsonld" => (Dir.glob("*.ttl").unshift("manifests.nt") - %w(earl.ttl)) do
  %x{earl-report --format json -o earl.jsonld *.ttl}
end

desc "Build Turtle"
file "earl.ttl" => "earl.jsonld" do
  %x{earl-report --json --format ttl -o earl.ttl earl.jsonld}
end

desc "Build HTML"
file "index.html" => "earl.jsonld" do
  %x{earl-report --json --format html --template template.haml -o index.html earl.jsonld}
end